### ISSUE TITLE
Pino stopped writing logs

### ISSUE THREAD

**Issue by HouganYT** [pinojs/pino#1845] opened 2023-11-02 08:29 UTC
We are experiencing exactly the same problems as the author of the other problem.
Look here for more details, screens and so on: https://github.com/pinojs/pino/issues/1829

We contacted author of related thread to see if he was able to fix the problem. [This advice](https://github.com/pinojs/pino/issues/1829#issuecomment-1757538273) from @mcollina helped fix the memory leak, but the logs still disappear and do not appear until the application is restarted.

So he closed issue, but problem still exists

A little information, we have several micro services on different versions of the node: 20.4, 20.7 - they are all experiencing problems.

We use a pino logger and also a nest pino
"nestjs-pino": "3.5.0",
"pino-logger": "8.14.1"
"pino-http": "8.3.3"

I would like to add that we have been using this logger for several years and have not experienced any problems. The only thing that has changed is that some time ago we upgraded to the node 20 and moved to the typescript 5

**Comment by mcollina** [comment] 2023-11-02 08:57
[`pino-logger`](https://www.npmjs.com/package/pino-logger) is a scam library that should not be used. Use [`pino`](https://npm.im/pino).

> I would like to add that we have been using this logger for several years and have not experienced any problems. 

This looks like a bug in Node.js more than Pino. Try setting `UV_USE_IO_URING=0` in your environment variables, as it might be necessary.

I would really need a way to reproduce this problem without:

1. Nest.js
2. Kubernetes

**Comment by habiiev** [comment] 2023-11-06 09:50
After 2 weeks of everything working as intended, we ran into the issue again.
This time we had a console.error on sonic boom for `drop` and some other events:
```typescript
  const stdoutStream = new SonicBoom({
    fd: stdout.fd,
    maxLength: 16 * mebibyteInBytes,
  });

  const onLogFailEventHandler =
    (event: string) => (error: (Error & { code: string }) | unknown) => {
      const errCodeStr =
        error instanceof Error && 'code' in error
          ? `, error code: ${error.code}`
          : '';

      console.error(
        `Encountered an error while trying to log (event: ${event}${errCodeStr})`,
        error,
      );
    };

  stdoutStream.on('drop', onLogFailEventHandler('drop'));
  // ... some other events
```

Other events didn't print, but the drop event is being printed a lot, basically at the same frequency as our logs (as expected).
The interesting thing is that when our drop event prints - a log from pino is being printed after it:

<img width="708" alt="Screenshot 2023-11-06 at 11 46 30" src="https://github.com/pinojs/pino/assets/31899678/55cc9864-8ca0-49da-8f37-cbcf12cf9990">

Will try using the `UV_USE_IO_URING` flag, and see how it goes.

**Comment by tomgrossman** [comment] 2023-11-18 18:26
facing the same issue here!! also after upgrading to Node 20.

**Comment by habiiev** [comment] 2023-11-28 08:19
@chrismeyers we haven't ran into the issue yet, everything is working fine at the moment

**Comment by TomKlaverAH** [comment] 2023-12-05 10:04
I ran into the same issue for an app running on Node 20.10.0 in Kubernetes.
`UV_USE_IO_URING=0` so far seems to fix the issue.
Additionally setting this flag has reduced the apps' CPU usage by a huge amount (60% or so). Haven't profiled the exact cause of this (yet).

**Comment by drakir** [comment] 2023-12-18 12:29
I´ve seen this same problem in one of our services running pino and node 20. One of the running kubernetes pods stop logging and memory keeps building up.

**Comment by Audarth** [comment] 2024-01-11 01:11
we've also been getting this issue on our production system, we're debating reverting back to node 18 or enabling `UV_USE_IO_URING=0  `

**Comment by mcollina** [comment] 2024-01-11 08:35
latest Node v18 also has io_uring enabled.

This is relevant: https://github.com/nodejs/node/issues/50717.

**Comment by asadtariq96** [comment] 2024-01-18 16:01
We are facing the same problem on node 18.18 and node 20.10
The pod logs stop, memory keeps increasing until the pod eventually dies.

**Comment by mcollina** [comment] 2024-01-18 16:04
@asadtariq96 could you confirm if setting `UV_USE_IO_URING=0` fixes it?

**Comment by chrismeyers** [comment] 2024-01-18 16:13
Reporting back on this.  We haven't seen any crashes after 4 weeks with `UV_USE_IO_URING=0` set.  Before, the app was crashing after 2-3 weeks.

**Comment by asadtariq96** [comment] 2024-01-18 16:14
> @asadtariq96 could you confirm if setting `UV_USE_IO_URING=0` fixes it?

@mcollina  I can get back to you after running some load tests with `UV_USE_IO_URING=0`
Meanwhile here's some heap snapshots. The `asJson` function seems to be the culprit. Is the following heap snapshot useful in any way?

![image](https://github.com/pinojs/pino/assets/18158879/71b5fc2a-8817-44bc-93a5-9c0a60a1a2a2)

**Comment by mcollina** [comment] 2024-01-18 16:27
That function generates the log lines that are getting accumulated in the buffer. The buffer is not flushed due to https://github.com/nodejs/node/issues/50717 in certain conditions on some (possibly old) docker/OS combinations.

**Comment by asadtariq96** [comment] 2024-01-18 16:41
Here's our config (if it helps)

`node:20.11.0-bookworm` with `jemalloc` running on GCP's GKE with `COS_CONTAINERED` OS

**Comment by asadtariq96** [comment] 2024-01-18 19:22
We ran some load tests with `UV_USE_IO_URING=0` and that seems to have fixed the problem 🚀

**Comment by santigimeno** [comment] 2024-02-09 11:38
Hello everyone. Libuv dev here, I'd like to take a look at this. Can somebody provide instructions (the simpler the better) on how to reproduce the issue? Thanks

**Comment by cometurrata** [comment] 2024-02-15 15:39
I think I have a similar issue Here, 

I'm not on Kubernetes, but on AWS ECS Fargate, with only 2 replicas, a relatively low number of HTTP queries

I also recently moved from node 18 to node 20 but this issue started to appear after some usage of AsyncLocalStorage but the behaviour is the same: 

* Logs stop being sent 
* Memory start increasing rapidly from some random time in the time
* Seems anyway correlated to the number of requests 

Our current workaround is to reboot instances regularly 👈 sorry for that  

Below, the blue spikes to 0 are the actual reboots of our instances

<img width="1441" alt="image" src="https://github.com/pinojs/pino/assets/23616466/668262d8-4fa6-478f-ab26-566d6b9083ab">


And my log count  with all repliquas  taken into account so it does not totally drops to 0 but is divided by 2, as if only one instance is not sending logs anymore 

<img width="1375" alt="image" src="https://github.com/pinojs/pino/assets/23616466/b1f285d4-7143-4e2a-a60d-ed8582f6c600">

**Comment by mcollina** [comment] 2024-02-15 20:48
The solution for you, and for all others is to set UV_USE_IO_URING=0.

**Comment by mcollina** [comment] 2024-02-15 20:57
@cometurrata your graphs are showing a long period of time, while Node v20.11.1 was released yesterday. I'm confident that Node v20.11.1 should not have the problem mentioned in this issue, because it disables io_uring by default.

Please open a fresh issue with fresh data and more details on your pino setup.

**Comment by mcollina** [comment] 2024-02-15 20:58
Closing this as latest Node.js has  io_uring disabled by default.

**Closed by mcollina** 2024-02-15 20:58 UTC
