### ISSUE TITLE
undefined (reading Symbol pino.nestedKey)

### ISSUE THREAD

**Issue by fraxken** [pinojs/pino#1446] opened 2022-05-30 11:01 UTC
Hello 👋,

Since few days (at least 2 weeks i think) we are facing an issue with pino which make our Fastify server to always reboot for a reason i fail to identify.

The only error and stacktrace i have of the issue:
![image](https://user-images.githubusercontent.com/4438263/170977301-aa8cba75-fc77-4dd0-9050-ac0a1f93f8af.png)

Doesn't seem to occur each time or with the same endpoints (so i guess that an issue with an internal who run time to time).

---

Node version: 16.13.1
Fastify: ^3.29.0
Pino version: 6.14.0 (taken on the server, i guess resolved with semver `^6.13.0` npm)

> Not sure if this is an issue with Fastify or pino itself.

**Comment by fraxken** [comment] 2022-05-30 11:06
It work in our production env with Fastify `^3.24.0`

**Comment by jsumners** [comment] 2022-05-30 13:13
Seeming duplicate of https://github.com/pinojs/pino/issues/956.

Regardless, v6 is no longer supported https://github.com/pinojs/pino/blob/22e0935b6da267f419a6f3e45f26e306202a18ed/docs/lts.md#schedule

**Closed by jsumners** 2022-05-30 13:13 UTC
