### ISSUE TITLE
missing control over the level format

### ISSUE THREAD

**Issue by PavelPolyakov** [pinojs/pino#363] opened 2018-02-21 15:38 UTC
Hello,

Once again thanks for the module. I met another issue during the attempts to shape it to my needs.
For some good reason it was decided that `level` in the logs is printed as `int`.

In my case I'd prefer to have it as string.

First I thought that I can overwrite it using `serializers`:

```js
const pino = require('pino');

const logger = pino({
    serializers: {
        allOk: v => {
            return 444;
        },
        level: v => {
            return pino.levels.labels[v];
        }
    }
})

logger.info({allOk: 333}, 'hello');
```

Result:
```
{"level":30,"time":1519227377898,"msg":"hello","pid":16280,"hostname":"PP-MacBook-Pro.local","allOk":444,"v":1}
```

But this doesn't work, probably because level is "core" log property. And serialisers are only applied to the properties of the objects you log.

Is there an expected way to manipulate the `level` and how it's displayed?

\* it is possible to do it using `prettyPrint`, but this is not an option, since I log into the custom stream.

Regards,

**Comment by mcollina** [comment] 2018-02-21 15:47
No there is not. The format is fixed for good reasons, the tools needs to process things in a consistent way. I don't see this changing in any forseeable future.

**Comment by PavelPolyakov** [comment] 2018-02-21 15:54
> The format is fixed for good reasons

I'm sure you have a reason for that.

Here is my use case:
1. logs => output
2. output => ElasticSearch
3. Than I search through the logs using Kibana
4. in Kibana I'm used to search by `AND level:"error"`

There are several solutions for this problem, including:
1. add another key to express the level as string - this leads to changing the `key` which shows the level
2. put something in the middle (like logstash) which'll convert number into the string - I see this as overhead

I do not suggest to change something, but to give control over this.

**Comment by jsumners** [comment] 2018-02-21 16:04
Duplicate of #279.

Also see https://github.com/pinojs/pino/issues/271#issuecomment-317545529

**Closed by jsumners** 2018-02-21 16:04 UTC
Labels: duplicate

**Comment by PavelPolyakov** [comment] 2018-02-21 16:10
@jsumners 
Thanks
