### ISSUE TITLE
Support the bunyan `level()` API

### ISSUE THREAD

**Issue by yunong** [pinojs/pino#276] opened 2017-08-02 05:18 UTC
We recently migrated to Pino, but have a bunch of teams still using `bunyan`, or expecting modules to pass them a `bunyan` object.

However, in Pino, `log.level` is an object, wheras in bunyan `log.level` is a function. This has the unfortunate effect of causing runtime errors whenever a module calls `log.level()` when passed a Pino logger instead of a bunyan logger.

The bunyan API is here: https://github.com/trentm/node-bunyan#levels and it looks like both `level` and `levels` are functions in bunyan but objects in Pino.

**Comment by mcollina** [comment] 2017-08-02 07:55
Ouch, this would be tricky and we will have to do a semver-major change. Is this a very common case, where someone changes the level of a logger from within an embedded file?

I am ok with this change, even if it might break some of our users. If we implement this we should just change the getter and maintain the setter as it currently is.

I'm ok with this change, as I was almost keen on removing the 'level' accessors several times, I just use `'level'`  when creating the logger itself.

Folks, what do you think?

cc @davidmarkclements @watson @jsumners

**Comment by jsumners** [comment] 2017-08-02 12:29
I think Bunyan did it wrong. A property is easier to work with than a getter and setter combination. But, while our readme merely says "inspired by Bunyan," I get the desire for API compatibility here. Except, Pino now has its own following with over 80,000 downloads in the last month. That's certainly not close to Bunyan's 1.6MM, but it's still a significant number of users and we have had plenty of issues from people specifically using the levels feature.

Given all of that, I'm tempted to say create a local wrapper for Pino that gives the desired interface and leave Pino itself as-is.

**Comment by davidmarkclements** [comment] 2017-08-02 12:37
Or a mode, enabled via options

**Comment by mcollina** [comment] 2017-08-02 13:10
> Bunyan did it wrong.

I disagree. Bunyan did the best he could do in an era where `Object.defineProperty` was not reliable. Bunyan is still awesome🥇 ! I would recommend them moving to properties, as they are much easier to work with anyway if ever they do a major release.

I'll see if I can assemble a PR based on a flag. It would probably be a global accessor on the module itself, as I would have to alter the prototype.

**Comment by mcollina** [comment] 2017-08-02 13:38
@yunong it seems the problem is more complex than this, as https://github.com/trentm/node-bunyan#levels speaks a lot about `levels()`. That would be *very* hard to emulate with pino-multi-stream. Maybe these fix should live just in `pino-multi-stream`?

**Closed** 2017-08-03 13:01 UTC
