### ISSUE TITLE
Dropping chars

### ISSUE THREAD

**Issue by ronag** [pinojs/pino#1261] opened 2021-12-10 13:52 UTC
e.g.

```js
{"level":10,"time":1639142154887,"pid":1,"hostname":"51a2eee7f0d9","name":"search","id":16273,"type":"simple","query":{"type":"simple","roles":["MTuMLU_4ZwXPSN","administrator"],"query":"types:panel -tags.keyword:nxt-master","count":1000,"deleted":faen":null,"sortBy":"-created","refreshInterval":10000},"refreshInterval":10000,"msg":"Refreshing search"}
```

Notice the part:

```
"deleted":faen"
```

Should be:

```
"deleted":false,"hidden":null
```

Missing:

```
lse,"hidd
```

We have other examples where a few chars seems to be missing.

```
pino.destination({ fd: process.stdout.fd, sync: false, minLength: 4096 })
```

```
sonic-boom@^2.2.0, sonic-boom@^2.2.1, sonic-boom@^2.3.1:
  version "2.4.1"
pino@^7.5.1:
  version "7.5.1"
thread-stream@^0.13.0:
  version "0.13.0"
```

Running in docker with `node:16.13.1`

The logs come directly from the console log, i.e. no file or anything involved.

**Comment by ronag** [comment] 2021-12-10 13:55
@mcollina FYI

**Comment by jsumners** [comment] 2021-12-10 14:02
Could this be due to the async buffer getting full and truncating lines? https://github.com/pinojs/thread-stream/pull/40#discussion_r738870485

**Comment by ronag** [comment] 2021-12-10 14:03
Could be

**Comment by ronag** [comment] 2021-12-10 14:05
Do we go through thread-stream even when writing to stdout? That seems unnecessary?

**Comment by ronag** [comment] 2021-12-10 14:18
If it thread-stream is in play here I suspect an issue with the overflow logic.

**Comment by mcollina** [comment] 2021-12-10 14:43
I think something that would help is a script to replicate the problem. I've tested this at the best I could and there is a test that writes a lot of data triggering the overflow multiple times.

**Comment by ronag** [comment] 2021-12-10 14:47
I haven't managed to create a repro yet... However, the following code is very suspicious:

https://github.com/pinojs/thread-stream/blob/main/index.js#L216-L226

There is a case here where if `flushing` we append to `buf` even if it will exceed `MAX_STRING`.

**Comment by mcollina** [comment] 2021-12-10 17:39
That code is essentially correct. In case the string exceed MAX_STRING, it triggers a writeSync with the current content of the buffer. writeSync then empties the buffer. Finally we add the new content to append to the Buffer.

**Comment by ronag** [comment] 2021-12-10 17:55
I think you are missing the flushing check?

**Comment by ronag** [comment] 2021-12-10 18:23
i.e.

```js
stream.write(maxStringLenString)
assert(stream[kState].flushing)
stream.write(maxStringLenString) // oops buf size will exceeds MAX_STRING
```

**Comment by ronag** [comment] 2021-12-10 18:37
See test/string-limit-2.test.js in https://github.com/pinojs/thread-stream/pull/55/files

**Comment by ronag** [comment] 2021-12-10 18:40
I'm not sure this is the problem I'm encountering in production but it's still something.

**Comment by mcollina** [comment] 2021-12-24 09:58
Did this happen again?  Were you able to reproduce it?

**Comment by ronag** [comment] 2021-12-24 10:01
Happens all the time in production. Don’t have a runnable repro. We were forced to change our service to log less and then the problem disappeared.

**Comment by mcollina** [comment] 2021-12-24 10:55
Very interesting. What transports are you using?

**Comment by ronag** [comment] 2021-12-24 13:35
Just normal stdout. The default. pino.destination with async true.

**Comment by ronag** [comment] 2021-12-24 13:35
My girlfriend will kill me if I take my computer out so I will have to get back later with the exact configuration. 😅

**Comment by ronag** [comment] 2021-12-27 07:55
@mcollina 

```js
stream = pino.destination({ fd: process.stdout.fd, sync: false, minLength: 4096 })
```

**Comment by mcollina** [comment] 2021-12-27 08:26
Is that being wrapped inside `pino.transport()`? why you are not using `pino.destination()` directly?

**Comment by ronag** [comment] 2021-12-27 08:28
```js
 if (!extreme) {
    stream = pino.destination({ fd: process.stdout.fd, sync: true })
  } else {
    stream = pino.destination({ fd: process.stdout.fd, sync: false, minLength: 4096 })
    setInterval(() => {
      logger.flush()
    }, flushInterval).unref()
  }

  const logger = pino(
    {
      serializers,
      prettyPrint, // TODO (fix): This is deprecated...
      level,
      ...options,
    },
    stream
  )
```

**Comment by ronag** [comment] 2021-12-27 08:29
Not explicitly using transport.

**Comment by mcollina** [comment] 2021-12-27 08:31
This is _definitely_ not about thread-stream but something in our old friend https://github.com/pinojs/sonic-boom.

**Comment by mcollina** [comment] 2021-12-27 08:34
It's unclear which version of sonic-boom are you using. Could you check if you are running the latest?

**Comment by ronag** [comment] 2021-12-27 08:35
```js
sonic-boom@^2.2.0, sonic-boom@^2.2.1, sonic-boom@^2.3.1:
  version "2.4.1"
  resolved "https://registry.yarnpkg.com/sonic-boom/-/sonic-boom-2.4.1.tgz#6e1c3762c677425c6ffbd7bd106c4f8258b45b39"
  integrity sha512-WgtVLfGl347/zS1oTuLaOAvVD5zijgjphAJHgbbnBJGgexnr+C1ULSj0j7ftoGxpuxR4PaV635NkwFemG8m/5w==
  dependencies:
    atomic-sleep "^1.0.0"
```

**Comment by mcollina** [comment] 2021-12-27 08:39
You might want to look into adding a test similar to https://github.com/pinojs/thread-stream/blob/main/test/string-limit.test.js to sonic-boom.

**Comment by RichAyotte** [comment] 2022-01-04 20:50
Adding a "me too" to this issue. I'm seeing this happen all the time in production, especially with the larger payloads. I just had one cut off at 61440 characters if that's a number of any significance. I'll look for other instances to see if there's a pattern.

**Comment by mcollina** [comment] 2022-01-05 10:43
Can you please try https://github.com/pinojs/sonic-boom/pull/128 and see if it fixes it?

**Comment by klon** [comment] 2022-02-13 16:18
We noticed that since upgrading to 7.6.2 from 6.13.2 we started seeing bad JSON output from pino intermittently. Lost characters mid string. Once it started happening on an instance we typically had to kill and restart nodejs process to get it to work again. Reverting to 6.13.2 resolves it.

**Comment by mcollina** [comment] 2022-02-13 20:52
@klon as I said to @ronag, we need a way to reproduce the problem to be able to fix it.

**Comment by mcollina** [comment] 2022-07-19 22:23
This was likely fixed by https://github.com/pinojs/sonic-boom/pull/137.

**Closed by mcollina** 2022-07-19 22:23 UTC
