### ISSUE TITLE
Can we support bundlers without bundler specific plugins?

### ISSUE THREAD

**Issue by segevfiner** [pinojs/pino#1465] opened 2022-06-15 20:59 UTC
I wonder if there is a way we can modify pino and thread-stream, possibly with new additional API or backwards incompatible changes, so that they can work with bundlers without requiring bundler specific plugins that set `__bundlerPathsOverrides`.

1. Webpack supports this syntax: https://webpack.js.org/guides/web-workers/, by default. Annoyingly I'm not sure there is a convenient way to just get at the worker file name without immediately passing it to `new Worker` though there might be hacks to do so or something poorly documented.
2. esbuild doesn't have core support for it, but you can get workers to work if you just supply them as entry points with bundling enabled as far as I can tell, or use a plugin such as https://github.com/mitschabaude/esbuild-plugin-inline-worker.
3. Rollup needs a plugin/loader https://www.npmjs.com/package/rollup-plugin-web-worker-loader or https://www.npmjs.com/package/rollup-plugin-workers.
4. Vite has  it's own support https://vitejs.dev/guide/features.html#import-with-constructors which is also similar 

All those options work with same variations or syntax of detecting `new Worker` or `require/import` with specific file extensions or prefixes. I'm not sure how well if at all, any of this work when the parameters to those are dynamic. So to support this without bundler plugins, we might need a new alternative interface that can match those expectations for any worker that we load dynamically.

**Comment by mcollina** [comment] 2022-06-16 16:39
I don't know if it's even possible, it would be awesome if it could.
Would you like to propose a new design with a prototype?

cc @ShogunPanda

**Comment by segevfiner** [comment] 2022-06-17 13:02
Well for starters. if we just start the worker in `thread-stream` using:
```js
const worker = new Worker(new URL('./lib/worker.js', import.meta.url), {
```

Then webpack 5 for example will correctly build it as a new separate chunk. The problem is that `worker.js` then continues to do a dynamic import using `realImport` and webpack doesn't seem to have a builtin way to just get the URL of a worker module rather than immediately starting it , and I'm not sure how we can get it do to so. The other problem is that different bundlers have different syntax for workers and we somehow need to support them.

**Comment by ShogunPanda** [comment] 2022-06-17 13:04
The problem is that webpack and probably others only work in ESM. Moreover, no example seems to be working with dynamic runtime paths.

One approach I could think of instead to support bundlers is to have pino explicitly require all needed files so that bundlers will embed them. Then, at runtime, the bundled file is recreated on the filesystem in a tmp folder and passed to Workers.

@mcollina WDYT?

**Comment by segevfiner** [comment] 2022-06-17 13:10
webpack in particular does work in CommonJS with the syntax I described.

**Comment by ShogunPanda** [comment] 2022-06-17 13:11
Do you mind posting an example of that? I tried locally and it was not working, so I wonder if forgot anything.

**Comment by segevfiner** [comment] 2022-06-17 14:56
Weird, it seems to not work when the module is CommonJS but it did work when the main module is ESM and imports the CommonJS thread-stream. As in, modifying it inside `thread-stream` seems to have worked, but if the entry is CommonJS and uses it, it doesn't work.

**Comment by ShogunPanda** [comment] 2022-06-17 14:57
That's exactly the point. Webpack documentation about workers clearly states that.

**Comment by ShogunPanda** [comment] 2022-06-17 17:37
I totally agree.
If you have the time, you could provide a PR there first and then we can revisit this.

**Comment by segevfiner** [comment] 2022-06-28 23:15
One idea that came to mind is if we had an alternate/additional interface for starting transports that looks kinda like this:
```ts
const transport = pino.transportWorker(
  new Worker(new URL('./node_modules/pino-pretty/worker.js', import.meta.url),
  {/* Options for worker */},
);
```

Where `worker.js` is a worker entry point that expects to be used with `transportWorker` which will pass it the options necessary to init it (`postMessage`), and will then behave as needed to be used as a transport by it without any additional workers.

We can then leave starting the worker to the user's code which can handle starting it in any way that is appropriate for his bundler.

It would have been nicer if there way a more universal way for libraries to handle/declare such workers across bundlers though...

**Comment by mcollina** [comment] 2022-06-29 00:00
That won't work because that file is outside of the bundle. If you can load things from node_modules, then you could skip bundling altogether and just load everything from there.

A slightly different alternative approach that could be investigated is to use the `eval` interface of Workers, creating a bundle-within-a-bundle scenario. This will remove the multiple entry points but you'll still need the bundler plugin.

**Comment by segevfiner** [comment] 2022-06-29 05:47
WebPack explicitly looks for that syntax and will generate a new entry bundle with that file, rewriting that expression to use it.

**Comment by mcollina** [comment] 2022-06-29 06:04
But then you'll have only one worker, and we'll need to keep all the complete transport code inside every module, making maintenance very complicated. Moreover, we won't be able to support multiple transports like it's possible now.

**Comment by mcollina** [comment] 2022-06-29 08:34
I'm going to close this as there is very little we can do as part of pino. Thanks for the great discussion.

Generically I would recommend to not bundle server-side code.

**Closed by mcollina** 2022-06-29 08:34 UTC

**Comment by segevfiner** [comment] 2022-06-29 08:40
Forced to use a CommonJS entrypoint and to minify/mangle the code, so I had to bundle to get it all working. 😢

**Comment by ShogunPanda** [comment] 2022-06-29 08:48
@segevfiner may I ask you a thing? Why do you need to bundle on the server?

**Comment by segevfiner** [comment] 2022-06-29 08:52
Needed to package using `pkg` which only supports a CommonJS entry point ATM, and I have pure ESM dependencies that will only work when bundled in this configuration. I also needed to minify/obfuscate the code, and I couldn't figure out a way to do so without a bundler.

We also have a VS Code extension where they recommended bundling to decrease distribution size and loading times and is also limited to a CommonJS entrypoint. (They have templates that do so).

**Comment by ShogunPanda** [comment] 2022-06-29 10:53
I see. Fine. :(
I just wanted to check if we could help with your setup. 
Good luck then!
