### ISSUE TITLE
using transport and serializer altogether

### ISSUE THREAD

**Issue by moeinrahimi** [pinojs/pino#1295] opened 2022-01-08 17:10 UTC
I'm trying to save logs based on levels to different files using the transport option and also I want to add some parameters to my logs so I decided to the serializer.
``` js

module.exports = require('pino')({
  transport: {
    targets: [
      {
        target: 'pino/file',
        options: { destination: '/var/log/bento/bento_info.log', mkdir: true },
        level: 'info',
      },
      {
        target: 'pino/file',
        options: { destination: '/var/log/bento/bento_error.log', mkdir: true },
        level: 'error',
      },
    ],
  },
  serializers: {
    res(reply) {
      return {
        statusCode: reply.statusCode,
      };
    },
    req(request) {
      return {
        method: request.method,
        url: request.url,
        custom:1
      };
    },
  },
});

Your Environment
node version: v14.16.1
fastify version: 3.15.1
os: Windows,
fastify version: 7.6.2




```
enabling serializer makes logger stops working. there is no warning or error message in output

**Comment by mcollina** [comment] 2022-01-08 17:59
duplicate of https://github.com/fastify/help/issues/598

**Closed by mcollina** 2022-01-08 17:59 UTC
