### ISSUE TITLE
Error Object Serialisation issue with `nestedKey` options

### ISSUE THREAD

**Issue by dhruvppatel** [pinojs/pino#771] opened 2020-02-12 14:16 UTC
Error object information is not serialized/included when `nestedKey` option is provided

Code
```
const pino = require('pino');

const logger = pino({
  prettyPrint: true,
  base: null,
});

const loggerWithNested = pino({
  prettyPrint: true,
  nestedKey: 'data',
  base: null,
});

console.log('----- Without nestedKey -------');
logger.error(new Error('an error'));
console.log('\n----- With nestedKey -------');
loggerWithNested.error(new Error('an error'));
```

Output
```
----- Without nestedKey -------
[1581516926814] ERROR: an error
    Error: an error
        at Object.<anonymous> (/opt/hotstar/applications/cricinfo/cric-info-api/src/sample.js:15:14)
        at Module._compile (internal/modules/cjs/loader.js:945:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
        at Module.load (internal/modules/cjs/loader.js:798:32)
        at Function.Module._load (internal/modules/cjs/loader.js:711:12)
        at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
        at internal/main/run_main_module.js:17:11

----- With nestedKey -------
[1581516926816] ERROR:
    data: {}
```

**Comment by jsumners** [comment] 2020-02-12 15:07
I think you'll need to add a serializer for the `data` property. You can use [`pino-std-serializers`](https://github.com/pinojs/pino-std-serializers) to bootstrap your custom serializer.

**Comment by VtoCorleone** [comment] 2020-02-27 21:35
I am running into a similar issue with API responses.  

When I upgrade to pino@5.16.0 and use the `nestedKey` option, the entire `res` and `req` properties are logged regardless of what serializers I have set which causes too much data to be logged. 

If I remove the `nestedKey` option with pino@5.16.0, everything logs as expected. 

```
const logger = require('pino')(
  {
    base: {
      appContext: {
        ip: ip.address(),
        name,
        version
      }
    },
    nestedKey: 'payload',
    level: LOG_LEVEL,
    prettyPrint: !ELASTICSEARCH_URL
  },
  elasticTransport
);

await server.register([
  {
    plugin: h2o2
  },
  {
    plugin: hapiPino,
    options: {
      prettyPrint: !config.ELASTICSEARCH_URL,
      ignorePaths: '/up',
      instance: logger,
      serializers: {
        err: err => ({
          type: err.type
        }),
        req: req => ({
          headers: req.headers
        }),
        res: res => ({
          headers: res.headers
        })
      }
    }
  }
]);

```

Here is what the `req` and `res` properties look like

```
req: {
      "headers": {
        "content-type": "application/json",
        "user-agent": "PostmanRuntime/7.21.0",
        "accept": "*/*",
        "cache-control": "no-cache",
        "postman-token": "8910c018-6280-47d2-b4ab-97bc590de718",
        "host": "localhost:21871",
        "accept-encoding": "gzip, deflate",
        "content-length": "671925",
        "connection": "keep-alive"
      }
    }
    res: {
      "headers": {
        "content-type": "application/json; charset=utf-8",
        "cache-control": "no-cache",
        "content-length": 62
      }
    }
```

Here are the libraries that I am using
```
"hapi": "17.8.5",
"pino": "5.16.0",
"pino-pretty": "3.5.0",
```

**Comment by VtoCorleone** [comment] 2020-02-28 02:25
@jsumners 

I was able to identify where the issue is.  

The code checks if the `nestedKey` property exists.  If it does, it wraps all objects under the specified `nestedKey` property.  So it will nest the `req`, `res` and `err` properties under the `nestedKey` property on response logging.

https://github.com/pinojs/pino/blob/master/lib/tools.js#L37

The problem is that when the code tries to run the serializers against the object, the `req`, `res` and `err` properties are nested and can't be found.  

https://github.com/pinojs/pino/blob/master/lib/tools.js#L94

I'm looking into creating a PR for this now.

**Comment by jsumners** [comment] 2020-02-28 13:17
Yes, that was the point of https://github.com/pinojs/pino/pull/759

By enabling the `nestedKey` option you are opting-in to every property that isn't a core Pino property, those which are essentially metadata about the log, being added to the specified "nest key". Thus, when `nestedKey` enabled doing `log.info({ req })` will result in the `{ req }` object being a child of the specified nesting key. Whereas without the `nestedKey` option enabled, the properties of `{ req }` will simply be added to the root log object.

Serializers work by inspecting the root level of the log object, e.g. the `msg` property. In normal operation that means the `req` serializer will look for `log.req` and serialize that property. But the `nestedKey` option makes that log object look like `log.nestKey.req` so the serializer cannot find it.

Thus my response that you will need to define a new serializer to accommodate whatever key you specified as the nesting key.

**Comment by VtoCorleone** [comment] 2020-02-28 14:29
Thanks for the quick response and being so thorough in the explanation! It makes complete sense now.

I was able to get the desired output by using the following options with the default pino serializers.

```
nestedKey: 'payload',
serializers: {
  payload: data => {
    if (data.req) {
      data.req = pino.stdSerializers.req(data.req);
    }

    if (data.res) {
      data.res = pino.stdSerializers.res(data.res);
    }

    if (data.err) {
      data.err = pino.stdSerializers.err(data.err);
    }

    return data;
  }
}
```

As for my part of this issue, I feel that the issue is resolved.

Do you think that that adding to the documentation about the use of `nestedKey` and `serializers` would be too verbose?  If not, I can try to draft something up.

**Comment by jsumners** [comment] 2020-02-28 14:48
Better documentation is always welcome.

**Comment by jsumners** [comment] 2020-03-18 21:37
I'm closing this as I believe it has been sufficiently answered.

**Closed** 2020-03-18 21:38 UTC

**Comment by fiznool** [comment] 2020-03-19 14:53
Thanks @VtoCorleone your code snippet helped me to workaround this.

For reference, I also added a conditional to support directly logging out an error object, i.e. `logger.error(err)`:

``` js
nestedKey: 'payload',
serializers: {
  payload: data => {
    if(data instanceof Error) {
      return pino.stdSerializers.err(data.err);
    }

    if (data.req) {
      data.req = pino.stdSerializers.req(data.req);
    }

    if (data.res) {
      data.res = pino.stdSerializers.res(data.res);
    }

    if (data.err) {
      data.err = pino.stdSerializers.err(data.err);
    }

    return data;
  }
}

**Comment by mfrye** [comment] 2020-09-14 02:53
> Thanks @VtoCorleone your code snippet helped me to workaround this.
> 
> For reference, I also added a conditional to support directly logging out an error object, i.e. `logger.error(err)`:
> 
> ```js
> nestedKey: 'payload',
> serializers: {
>   payload: data => {
>     if(data instanceof Error) {
>       return pino.stdSerializers.err(data.err);
>     }
> 
>     if (data.req) {
>       data.req = pino.stdSerializers.req(data.req);
>     }
> 
>     if (data.res) {
>       data.res = pino.stdSerializers.res(data.res);
>     }
> 
>     if (data.err) {
>       data.err = pino.stdSerializers.err(data.err);
>     }
> 
>     return data;
>   }
> }
> ```

A helpful note for whoever finds this, note that the first check for an error here should just pass the error instead of data.err.

```js
if (data instanceof Error) {
   return pino.stdSerializers.err(data);
}
```

**Comment by Repraance** [comment] 2021-07-07 10:30
There's still problem. By adding serializers for nestedKey, the error object is well printed. But the `msg` which should be the message of the error is still missing.
