### ISSUE TITLE
Test issue in CITGM

### ISSUE THREAD

**Issue by targos** [pinojs/pino#1215] opened 2021-11-10 08:42 UTC
See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2791/nodes=fedora-last-latest-x64/testReport/junit/(root)/citgm/pino_v7_1_0/

```
not ok 33 - test/transport/pipeline.test.js # time=2629.015ms
   ---
   env: {}
   file: test/transport/pipeline.test.js
   timeout: 480000
   command: /home/iojs/build/workspace/citgm-smoker/smoker/bin/node
   args:
     - test/transport/pipeline.test.js
   stdio:
     - 0
     - pipe
     - 2
   cwd: /home/iojs/tmp/citgm_tmp/b8504092-42e9-4a15-89fa-85afcd6853bc/pino
   exitCode: 1
   ...
 {
     # Subtest: pino.transport with a pipeline
         not ok 1 - /home/iojs/tmp/citgm_tmp/b8504092-42e9-4a15-89fa-85afcd6853bc/npm_config_tmp/_lqhwaguae was not created.
           ---
           stack: |
             Timeout.<anonymous> (test/helper.js:70:16)
           at:
             line: 70
             column: 16
             file: test/helper.js
             function: Timeout.<anonymous>
           tapCaught: returnedPromiseRejection
           test: pino.transport with a pipeline
           source: |2
                     clearInterval(interval)
                     reject(new Error(`${filename} was not created.`))
             ---------------^
                   }
                 }, INTERVAL)
           ...
         
         1..1
         # failed 1 test
     not ok 1 - pino.transport with a pipeline # time=2386.023ms
     
     1..1
     # failed 1 test
     # time=2629.015ms
 }
```

**Comment by mcollina** [comment] 2021-11-10 09:03
This is node v17, correct? https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2791/#showFailuresLink

**Comment by targos** [comment] 2021-11-10 09:20
> This is node v17, correct? https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2791/#showFailuresLink

Yes. I don't know if its v17-specific though.

**Comment by voxpelli** [comment] 2021-11-15 16:13
The cause seems to be a timeout.

I opened #1219 to clarify the error message and I would propose raising the timeout from 2 seconds to something more to see if that helps.

**Comment by mcollina** [comment] 2021-11-15 16:20
seems valuable!

**Comment by mcollina** [comment] 2021-11-25 17:06
CITGM run for pino: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2794/

**Comment by mcollina** [comment] 2021-11-29 14:25
@voxpelli @targos it seems going better now. Could I close this? Or would you still work from our end?

**Comment by targos** [comment] 2021-11-29 14:27
seems ok from my pov

**Closed** 2021-11-29 14:44 UTC
