### ISSUE TITLE
Windows: incorrect encoding on Unicode output

### ISSUE THREAD

**Issue by budarin** [pinojs/pino#548] opened 2018-11-20 19:24 UTC
I try to log
```bash
logger.info(`Сервер запущен по адресу:')
```
but see in log
```bash
{"level":30,"time":1542741475885,"msg":"╨б╨╡╤А╨▓╨╡╤А ╨╖╨░╨┐╤Г╤Й╨╡╨╜ ╨┐╨╛ ╨░╨┤╤А╨╡╤Б╤Г:
```

**Comment by budarin** [comment] 2018-11-20 19:29
no
here is logger configuration
```js
import pino from 'pino';

const dest = pino.extreme();
const logger = pino(dest);
setInterval(() => logger.flush(), 10000).unref();

export default logger;
```

**Comment by davidmarkclements** [comment] 2018-11-20 19:30
I'm not able to reproduce 

![image](https://user-images.githubusercontent.com/1190716/48797659-16eb3c00-ed03-11e8-886f-c06d43f79446.png)

**Comment by davidmarkclements** [comment] 2018-11-20 19:32
also verified to work with `pino.extreme`

![image](https://user-images.githubusercontent.com/1190716/48797742-531e9c80-ed03-11e8-8989-cf69a81822c7.png)

**Comment by davidmarkclements** [comment] 2018-11-20 19:33
redirecting to file, works: 

![image](https://user-images.githubusercontent.com/1190716/48797841-8e20d000-ed03-11e8-807f-6982b4385f1f.png)

**Comment by budarin** [comment] 2018-11-20 19:34
![default](https://user-images.githubusercontent.com/8055157/48797873-625a1600-ed14-11e8-8875-d45509a32270.png)

**Comment by davidmarkclements** [comment] 2018-11-20 19:35
it might be due to the fact your transpiling your server

try

```
process.stdout.write(`Сервер запущен по адресу:`)
```

**Comment by davidmarkclements** [comment] 2018-11-20 19:37
or otherwise I'm seeing that the output is being escaped, so something is processing the output 

closing for now, as  I'm certain this isn't a problem with Pino

**Comment by budarin** [comment] 2018-11-20 19:40
strange - writing into stdout is working right

![default](https://user-images.githubusercontent.com/8055157/48798228-38edba00-ed15-11e8-8aab-7427533adde1.png)

**Comment by jsumners** [comment] 2018-11-20 20:31
Oh boy. How has this not come up before?

To be JSON spec compliant we should be outputting UTF-8 strings. I'm not seeing anything in the language spec that that dictates how strings are to be encoded -- https://tc39.github.io/ecma262/#sec-text-processing . But this article implies that they could be UTF-16, and a comment to it indicates they could very well be merely ASCII, -- https://kev.inburke.com/kevin/node-js-string-encoding/

Regarding the problem, I suspect it has to do with the encoding of the destination. So if `process.stdout` isn't in UTF-8 mode you are likely to get garbage.

**Comment by davidmarkclements** [comment] 2018-11-20 20:47
Ok reopening as it looks like this might be on us - or more likely - sonic-boom cc @mcollina 

@budarin - as a workaround try `pino(process.stdout)`

**Comment by budarin** [comment] 2018-11-20 20:55
this is only apparent in Windows
have verified on MacOS - everything is ok

**Comment by davidmarkclements** [comment] 2018-11-20 21:05
The thing is `sonic-boom` does support UTF-8  (https://github.com/mcollina/sonic-boom/blob/master/index.js#L71) so this problem might go all the way to Node core

**Comment by mcollina** [comment] 2018-11-21 17:02
Turns out it's a known limitation of Node.js.

Running `chcp 65001` https://ss64.com/nt/chcp.html solves the problem for me.

I propose we just document this behavior in the pino website https://getpino.io/#/docs/help.

**Comment by mcollina** [comment] 2018-11-21 17:06
Thanks @refack in https://github.com/nodejs/node/issues/24550#issuecomment-440720503.

**Closed** 2018-11-22 17:14 UTC
Labels: bug
